---
# tasks file for dns
- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ hostvars[item].ansible_host }}$'
    line: "{{ hostvars[item].ansible_facts.default_ipv4.address }} {{ hostvars[item].ansible_host }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"